[package]
name = "mfm-artifact-store-s3"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
mfm-machine = { path = "../../machine" }
s3 = { package = "rust-s3", version = "0.37.1", default-features = false, features = ["tokio-rustls-tls"] }

[dev-dependencies]

[features]
parity-tests = []
