[package]
name = "mfm-artifact-store-s3"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
mfm-machine = { path = "../../machine" }
s3 = { package = "rust-s3", version = "0.37.1", default-features = false, features = ["tokio-rustls-tls"] }

[dev-dependencies]
mfm-machine-test-support = { path = "../../machine-test-support" }
tempfile = "3.8"
tokio = { workspace = true }

[features]
parity-tests = []
