[package]
name = "mfm-op-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde_json = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-op-common = { path = "../../states/common" }

[dev-dependencies]
tokio = { workspace = true }
