[package]
name = "mfm-op-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
mfm-canonical = { path = "../../kernel/canonical" }
mfm-certify = { path = "../../kernel/certify" }
mfm-collectors-proof = { path = "../../collectors/proof" }
mfm-ids = { path = "../../kernel/ids" }
mfm-program = { path = "../../kernel/program" }

[dev-dependencies]
