[package]
name = "mfm"
version = "0.1.29"
edition = "2021"

[dependencies]
serde_yaml = "0.9"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-client = { workspace = true }
alloy-transport-http = { workspace = true }
alloy-signer = { workspace = true }
url = "2.5"
mfm_core = { path = "../mfm_core" }
mfm_machine = { path = "../mfm_machine" }
hex = "0.4.3"
ring = { workspace = true }
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1.0"
anyhow = "1.0.75"

[[bin]]
name = "mfm_cli"
path = "src/main.rs"

