[package]
name = "mfm"
version = "0.1.29"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
mfm_core = { path = "../mfm_core" }
mfm_machine = { path = "../mfm_machine" }

# Dependencies moved from workspace
serde_yaml = "0.9"
serde_json = "1.0.108"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.44", features = ["full"] }
alloy-primitives = "1.0.1"
alloy-provider = "1.0.1"
alloy-rpc-client = "1.0.1"
alloy-transport-http = "1.0.1"
alloy-signer = "1.0.1"
url = "2.5"
hex = "0.4"
ring = "0.17.14"
thiserror = "2.0"
anyhow = "1.0.75"

[[bin]]
name = "mfm_cli"
path = "src/main.rs"
