[package]
name = "mfm-op-evm-write"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
alloy-primitives = { workspace = true }
k256 = { version = "0.13", features = ["ecdsa"] }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-collectors-evm = { path = "../../collectors/evm" }
mfm-op-common = { path = "../common" }
zeroize = "1.7.0"
