[package]
name = "mfm-op-evm-write"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-state-common = { path = "../../states/common" }
mfm-evm-dcv-model = { path = "../../evm-dcv-model" }
mfm-evm-runtime = { path = "../../evm-runtime" }

[dev-dependencies]
mfm-collectors-evm = { path = "../../collectors/evm" }
