[package]
name = "mfm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.79"
serde = { version = "1.0", features = ["derive"] }
ethsign = "0.8"
rustc-hex = "2.1.0"
web3 = "0.18.0"
