[package]
name = "mfm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.79"
serde = { version = "1.0", features = ["derive"] }
rustc-hex = "2.1.0"
tokio = { version = "1.17.0", features = ["full"] }
secp256k1 =  "0.21"
# secp256k1 = { version = "0.21", features = ["recovery"], optional = true }
# once_cell = { version = "1.8.0", optional = true }
web3 = { version = "0.18.0" }
# futures = "0.3.21"

# [features]
# signing = ["secp256k1", "once_cell"]