wallets:
  test-wallet:
    private_key: YOUR_PRIVATE_KEY

withdraw_wallets:
  test-wallet2:
    address: YOUR_PUBLIC_ADDRESS

networks:
  bsc:
    name: bsc
    symbol: bnb
    chain_id: 56
    rpc_url: https://bsc-dataseed.binance.org
    blockexplorer_url: https://bscscan.com
    min_balance_coin: 0.1
    wrapped_asset: wbnb

exchanges:
  pancake_swap_v2:
    name: pancake_swap_v2
    router_address: 0x10ED43C718714eb63d5aA57B78B54704E256024E
    factory_address: 0xca143ce32fe78f1f7019d7d551a6402fc5350c73
    network_id: bsc

assets:
  anonq:
    name: anonq
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xf393138616cd6DD367171eaA59c2eaEE420a32b9
    slippage: 2
  busd:
    name: busd
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
    slippage: 1
  wbnb:
    name: wbnb
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
    slippage: 1
  eth:
    name: eth
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0x2170ed0880ac9a755fd29b2688956bd959f933f8
    slippage: 2
  btcb:
    name: btcb
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c
    slippage: 2
  cake:
    name: cake
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
    slippage: 2

routes:
  busd-cake:
    base: busd
    quote: cake
    path: []
  cake-busd:
    base: cake
    quote: busd
    path: []
  busd-posi:
    base: busd
    quote: posi
    path: []
  posi-busd:
    base: posi
    quote: busd
    path: []
  busd-btcb:
    base: busd
    quote: btcb
    path: []
  busd-eth:
    base: busd
    quote: eth
    path: []
  wbnb-btcb:
    base: wbnb
    quote: btcb
    path: []
  wbnb-eth:
    base: wbnb
    quote: eth
    path: []
  btcb-wbnb:
    base: btcb
    quote: wbnb
    path: []
  eth-wbnb:
    base: eth
    quote: wbnb
    path: []
  btcb-busd:
    base: btcb
    quote: busd
    path: []
  eth-busd:
    base: eth
    quote: busd
    path: []
  btcb-anonq:
    base: btcb
    quote: anonq
    path: [wbnb]
  eth-anonq:
    base: eth
    quote: anonq
    path: [wbnb]
  anonq-btcb:
    base: anonq
    quote: btcb
    path: [wbnb]
  anonq-eth:
    base: anonq
    quote: eth
    path: [wbnb]
  anonq-busd:
    base: anonq
    quote: busd
    path: [wbnb]
  busd-anonq:
    base: busd
    quote: anonq
    path: [wbnb]
  wbnb-anonq:
    base: wbnb
    quote: anonq
    path: []
  wbnb-busd:
    base: wbnb
    quote: busd
    path: []
  busd-wbnb:
    base: busd
    quote: wbnb
    path: []
  anonq-wbnb:
    base: anonq
    quote: wbnb
    path: []

rebalancers:
  test-rebalancer:
    wallet_id: test-wallet
    name: test-anonq-busd
    portfolio:
      anonq:
        percent: 40
      busd:
        percent: 25
      wbnb:
        percent: 25
      eth:
        percent: 5
      btcb:
        percent: 5
    # if zero, always run
    threshold_percent: 2
    quoted_in: busd
    parking_asset_id: busd
    parking_asset_min_move: 0.01

yield_farms:
  posi-farm-bnb-posi:
    name: posi-farm-bnb-posi
    contract_name: position_stake_manager
    address: 0x0c54b0b7d61de871db47c3ad3f69feb0f2c8db0b
    wallet_id: farm-wallet
    asset_id: posi
    network_id: bsc
    operation: posi_farm_bnb_posi
    min_rewards_required: 10
    #quoted_asset_id: busd
  posi-farm-busd-posi:
    name: posi-farm-busd-posi
    contract_name: position_stake_manager
    address: 0x0c54b0b7d61de871db47c3ad3f69feb0f2c8db0b
    wallet_id: farm-wallet
    asset_id: posi
    network_id: bsc
    operation: posi_farm_busd_posi
    min_rewards_required: 10
  auto-cake:
    name: auto-cake
    contract_name: pancake_swap_auto_cake_pool
    address: 0xa80240eb5d7e05d3f250cf000eec0891d00b51cc
    wallet_id: farm-wallet
    asset_id: cake
    network_id: bsc
    operation: cake_auto_pool
    min_rewards_required: 1
# machine:
#   farm-all-to-busd-vault:
#     operations:
#       collect_farms_and_swap:
#         swap_to_asset_id: busd
#         yield-farms:
#           auto-cake:
#             yield_farm_id: auto-cake
#           posi-farm-bnb-posi:
#             yield_farm_id: posi-farm-bnb-posi
#           posi-farm-busd-posi:
#             yield_farm_id: posi-farm-busd-posi
#       withdraw:
#         wallet_id: farm-wallet
#         withdraw_wallet_id: busd-vault
