wallets:
  test-wallet:
    private_key: YOUR_PRIVATE_KEY

networks:
  bsc:
    name: bsc
    symbol: bnb
    chain_id: 56
    rpc_url: https://bsc-dataseed.binance.org
    blockexplorer_url: https://bscscan.com
    min_balance_coin: 0.1
    wrapped_asset: wbnb

exchanges:
  pancake_swap_v2:
    name: pancake_swap_v2
    router_address: 0x10ED43C718714eb63d5aA57B78B54704E256024E
    network_id: bsc

assets:
  anonq:
    name: anonq
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xf393138616cd6DD367171eaA59c2eaEE420a32b9
  busd:
    name: busd
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
  wbnb:
    name: wbnb
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c

routes: 
  anonq-busd:
    base: anonq
    quote: busd
    path: [wbnb]
  busd-anonq:
    base: busd
    quote: anonq
    path: [wbnb]
  wbnb-anonq:
    base: wbnb
    quote: anonq
    path: []
  wbnb-busd:
    base: wbnb
    quote: busd
    path: []
  busd-wbnb:
    base: busd
    quote: wbnb
    path: []
  anonq-wbnb:
    base: anonq
    quote: wbnb
    path: []

rebalancers:
  test-anonq-busd:
    wallet_id: test-wallet
    name: test-anonq-busd
    portfolio:
      anonq:
        percent: 50
      busd: 
        percent: 25
      wbnb:
        percent: 25
    # if zero, always run
    threshold_percent: 2 
    quoted_in: busd
    parking_asset_id: busd
