wallets:
  test-wallet:
    private_key: YOUR_PRIVATE_KEY
    encrypted: true
  farm-wallet:
    private_key: YOUR_PRIVATE_KEY

withdraw_wallets:
  test-wallet2:
    address: YOUR_PUBLIC_ADDRESS

networks:
  bsc:
    name: bsc
    symbol: bnb
    chain_id: 56
    rpc_url: https://bsc-dataseed.binance.org
    blockexplorer_url: https://bscscan.com
    min_balance_coin: 0.1
    wrapped_asset: wbnb
    decimals: 18
  polygon:
    name: polygon
    symbol: matic
    chain_id: 137
    rpc_url: https://polygon-rpc.com/
    blockexplorer_url: https://polygonscan.com/
    min_balance_coin: 1
    wrapped_asset: wmatic
    decimals: 18

exchanges:
  pancake_swap_v2:
    name: pancake_swap_v2
    router_address: 0x10ED43C718714eb63d5aA57B78B54704E256024E
    factory_address: 0xca143ce32fe78f1f7019d7d551a6402fc5350c73
    network_id: bsc
  quickswap_v2:
    name: quickswap_v2
    router_address: 0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff
    factory_address: 0x5757371414417b8c6caad45baef941abc7d3ab32
    network_id: polygon
  sushi_swap_polygon:
    name: susih_swap_polygon
    router_address: 0x1b02da8cb0d097eb8d57a175b88c7d8b47997506
    factory_address: 0xc35dadb65012ec5796536bd9864ed8773abc74c4
    network_id: polygon

rebalancers:
  test-rebalancer:
    name: test-anonq-busd
    network_id: bsc
    wallet_id: test-wallet
    portfolio:
      anonq:
        percent: 40
      busd:
        percent: 25
      wbnb:
        percent: 25
      eth:
        percent: 5
      btc:
        percent: 5
    strategy: full_parking #diff_parking
    # if zero, always run
    threshold_percent: 2
    quoted_in: busd
    parking_asset_id: busd
    parking_asset_min_move: 0.01

yield_farms:
  posi-farm-bnb-posi:
    name: posi-farm-bnb-posi
    contract_name: position_stake_manager
    address: 0x0c54b0b7d61de871db47c3ad3f69feb0f2c8db0b
    wallet_id: farm-wallet
    network_id: bsc
    operation: posi_farm_bnb_posi
    min_rewards_required: 10
    reward_asset_id: posi
  posi-farm-busd-posi:
    name: posi-farm-busd-posi
    contract_name: position_stake_manager
    address: 0x0c54b0b7d61de871db47c3ad3f69feb0f2c8db0b
    wallet_id: farm-wallet
    network_id: bsc
    operation: posi_farm_busd_posi
    min_rewards_required: 10
    deposit_asset_id:
    reward_asset_id: posi
  posi-baby-pool:
    name: posi-baby-pool
    contract_name: posi_smartchief
    address: 0xac1538061ad0694e2c0ef68b7fb94a091d448d99
    wallet_id: farm-wallet
    network_id: bsc
    operation: posi_pool_baby
    min_rewards_required: 7
    deposit_asset_id: posi
    reward_asset_id: baby
  auto-cake:
    name: auto-cake
    contract_name: pancake_swap_auto_cake_pool
    address: 0xa80240eb5d7e05d3f250cf000eec0891d00b51cc
    wallet_id: farm-wallet
    network_id: bsc
    operation: cake_auto_pool
    min_rewards_required: 1
    deposit_asset_id: cake
    reward_asset_id: cake
  auto-baby:
    name: auto-baby
    contract_name: pancake_swap_auto_cake_pool
    address: 0x3e1ead5cbe817689f4bdb96bceeb112fdbe94dbc
    wallet_id: farm-wallet
    network_id: bsc
    operation: baby_auto_baby_pool
    min_rewards_required: 1
    deposit_asset_id: baby
    reward_asset_id: baby

  #TODO: change the allowance to use different types of address, including farms
  auto-pacoca:
    name: auto-pacoca
    contract_name: pacoca_vault
    address: 0x16205528a8f7510f4421009a7654835b541bb1b9
    wallet_id: farm-wallet
    network_id: bsc
    operation: pacoca_auto_pool
    min_rewards_required: 100
    deposit_asset_id: pacoca
    reward_asset_id: pacoca
  maifinance-qi-wmatic:
    name: maifinance-qi-wmatic
    contract_name: qi_dao_staking_pool
    address: 0x574fe4e8120c4da1741b5fd45584de7a5b521f0f
    wallet_id: polygon-wallet
    network_id: polygon
    operation: qi_dao_staking_pool_qi_wmatic
    min_rewards_required: 10
    deposit_asset_id:
    reward_asset_id: qidao
  # quickswap-dual-matic-usdc:
  #   name: quickswap-dual-matic-usdc
  #   contract_name: quickswap_dual_rewards
  #   address: 0x14977e7e263ff79c4c3159f497d9551fbe769625
  #   wallet_id: polygon-wallet
  #   asset_id: qidao
  #   network_id: polygon
  #   operation: qi_dao_staking_pool_qi_wmatic
  #   min_rewards_required: 1

# machines:
#   farm-all-to-busd-vault:
#     name: farm-all-to-busd-vault
#     operations:
#       collect_farms_and_swap:
#         swap_to_asset_id: busd
#         yield-farms:
#           auto-cake:
#             yield_farm_id: auto-cake
#           posi-farm-bnb-posi:
#             yield_farm_id: posi-farm-bnb-posi
#           posi-farm-busd-posi:
#             yield_farm_id: posi-farm-busd-posi
#       withdraw:
#         wallet_id: farm-wallet
#         withdraw_wallet_id: busd-vault

assets:
  qidao:
    kind: token
    networks:
      polygon:
        name: qidao
        network_id: polygon
        exchange_id: quickswap_v2
        address: 0x580a84c73811e1839f75d86d75d88cca0c241ff4
        slippage: 2
        path_asset: weth
  dquick:
    kind: token
    networks:
      polygon:
        name: dquick
        network_id: polygon
        exchange_id: quickswap_v2
        address: 0xf28164a485b0b2c90639e47b0f377b4a438a16b1
        slippage: 2
        path_asset: weth
  xrp:
    kind: token
    networks:
      bsc:
        name: xrp
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE
        slippage: 2
        path_asset: wbnb
  link:
    kind: token
    networks:
      bsc:
        name: link
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD
        slippage: 2
        path_asset: wbnb
  gala:
    kind: token
    networks:
      bsc:
        name: gala
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x7dDEE176F665cD201F93eEDE625770E2fD911990
        slippage: 2
        path_asset: wbnb
  near:
    kind: token
    networks:
      bsc:
        name: near
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x1Fa4a73a3F0133f0025378af00236f3aBDEE5D63
        slippage: 2
        path_asset: wbnb
  luna:
    kind: token
    networks:
      bsc:
        name: luna
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x156ab3346823B651294766e23e6Cf87254d68962
        slippage: 2
        path_asset: wbnb
  wmatic:
    kind: token
    networks:
      bsc:
        name: wmatic
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0xcc42724c6683b7e57334c4e856f4c9965ed682bd
        slippage: 2
        path_asset: wbnb
      polygon:
        name: wmatic
        network_id: polygon
        exchange_id: sushi_swap_polygon
        address: 0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270
        slippage: 2
        path_asset: weth
  anonq:
    kind: token
    networks:
      bsc:
        name: anonq
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0xf393138616cd6DD367171eaA59c2eaEE420a32b9
        slippage: 2
        path_asset: wbnb
  busd:
    kind: token
    networks:
      bsc:
        name: busd
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
        slippage: 2
        path_asset: wbnb
  wbnb:
    kind: token
    networks:
      bsc:
        name: wbnb
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
        slippage: 2
        path_asset: wbnb
  weth:
    kind: token
    networks:
      bsc:
        name: weth
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x2170ed0880ac9a755fd29b2688956bd959f933f8
        slippage: 2
        path_asset: wbnb
      polygon:
        name: weth
        network_id: polygon
        exchange_id: sushi_swap_polygon
        address: 0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619
        slippage: 2
        path_asset: weth
  btc:
    kind: token
    networks:
      bsc:
        name: btc
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c
        slippage: 2
        path_asset: wbnb
  sol:
    kind: token
    networks:
      bsc:
        name: sol
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x570A5D26f7765Ecb712C0924E4De545B89fD43dF
        slippage: 2
        path_asset: wbnb
  posi:
    kind: token
    networks:
      bsc:
        name: posi
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x5ca42204cdaa70d5c773946e69de942b85ca6706
        slippage: 2
        path_asset: wbnb
  cake:
    kind: token
    networks:
      bsc:
        name: cake
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
        slippage: 2
        path_asset: wbnb
  pacoca:
    kind: token
    networks:
      bsc:
        name: pacoca
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x55671114d774ee99d653d6c12460c780a67f1d18
        slippage: 1
        path_asset: wbnb
  safemoon:
    kind: token
    networks:
      bsc:
        name: safemoon
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x42981d0bfbAf196529376EE702F2a9Eb9092fcB5
        slippage: 1
        path_asset: wbnb
  grt:
    kind: token
    networks:
      polygon:
        name: grt
        network_id: polygon
        exchange_id: sushi_swap_polygon
        address: 0x5fe2b58c013d7601147dcdd68c143a77499f5531
        slippage: 1
        path_asset: weth
  usdc:
    kind: token
    networks:
      polygon:
        name: usdc
        network_id: polygon
        exchange_id: sushi_swap_polygon
        address: 0x2791bca1f2de4661ed88a30c99a7a9449aa84174
        slippage: 1
        path_asset: wmatic
      bsc:
        name: usdc
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d
        slippage: 1
        path_asset: wbnb
  usdt:
    kind: token
    networks:
      bsc:
        name: usdt
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x55d398326f99059ff775485246999027b3197955
        slippage: 1
        path_asset: wbnb
  baby:
    kind: token
    networks:
      bsc:
        name: baby
        network_id: bsc
        exchange_id: pancake_swap_v2
        address: 0x53e562b9b7e5e94b81f10e96ee70ad06df3d2657
        slippage: 1
        path_asset: usdt
