wallets:
  test-wallet:
    private_key: YOUR_PRIVATE_KEY

withdraw_wallets:
  test-wallet2:
    address: YOUR_PUBLIC_ADDRESS

networks:
  bsc:
    name: bsc
    symbol: bnb
    chain_id: 56
    rpc_url: https://bsc-dataseed.binance.org
    blockexplorer_url: https://bscscan.com
    min_balance_coin: 0.1
    wrapped_asset: wbnb
  polygon:
    name: polygon
    symbol: matic
    chain_id: 137
    rpc_url: https://polygon-rpc.com/
    blockexplorer_url: https://polygonscan.com/
    min_balance_coin: 1
    wrapped_asset: wmatic

exchanges:
  pancake_swap_v2:
    name: pancake_swap_v2
    router_address: 0x10ED43C718714eb63d5aA57B78B54704E256024E
    factory_address: 0xca143ce32fe78f1f7019d7d551a6402fc5350c73
    network_id: bsc
  quickswap_v2:
    name: quickswap_v2
    router_address: 0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff
    factory_address: 0x5757371414417b8c6caad45baef941abc7d3ab32
    network_id: polygon

assets:
  dquick:
    name: wmatic
    network_id: polygon
    exchange_id: quickswap_v2
    address: 0xf28164a485b0b2c90639e47b0f377b4a438a16b1
    slippage: 2
  wmatic:
    name: wmatic
    network_id: polygon
    exchange_id: quickswap_v2
    address: 0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270
    slippage: 2
  anonq:
    name: anonq
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xf393138616cd6DD367171eaA59c2eaEE420a32b9
    slippage: 2
  busd:
    name: busd
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
    slippage: 1
  wbnb:
    name: wbnb
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
    slippage: 1
  eth:
    name: eth
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0x2170ed0880ac9a755fd29b2688956bd959f933f8
    slippage: 2
  btcb:
    name: btcb
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c
    slippage: 2
  cake:
    name: cake
    network_id: bsc
    exchange_id: pancake_swap_v2
    address: 0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
    slippage: 2

rebalancers:
  test-rebalancer:
    wallet_id: test-wallet
    name: test-anonq-busd
    portfolio:
      anonq:
        percent: 40
      busd:
        percent: 25
      wbnb:
        percent: 25
      eth:
        percent: 5
      btcb:
        percent: 5
    # if zero, always run
    threshold_percent: 2
    quoted_in: busd
    parking_asset_id: busd
    parking_asset_min_move: 0.01

yield_farms:
  posi-farm-bnb-posi:
    name: posi-farm-bnb-posi
    contract_name: position_stake_manager
    address: 0x0c54b0b7d61de871db47c3ad3f69feb0f2c8db0b
    wallet_id: farm-wallet
    asset_id: posi
    network_id: bsc
    operation: posi_farm_bnb_posi
    min_rewards_required: 10
    #quoted_asset_id: busd
  posi-farm-busd-posi:
    name: posi-farm-busd-posi
    contract_name: position_stake_manager
    address: 0x0c54b0b7d61de871db47c3ad3f69feb0f2c8db0b
    wallet_id: farm-wallet
    asset_id: posi
    network_id: bsc
    operation: posi_farm_busd_posi
    min_rewards_required: 10
  auto-cake:
    name: auto-cake
    contract_name: pancake_swap_auto_cake_pool
    address: 0xa80240eb5d7e05d3f250cf000eec0891d00b51cc
    wallet_id: farm-wallet
    asset_id: cake
    network_id: bsc
    operation: cake_auto_pool
    min_rewards_required: 1
# machine:
#   farm-all-to-busd-vault:
#     operations:
#       collect_farms_and_swap:
#         swap_to_asset_id: busd
#         yield-farms:
#           auto-cake:
#             yield_farm_id: auto-cake
#           posi-farm-bnb-posi:
#             yield_farm_id: posi-farm-bnb-posi
#           posi-farm-busd-posi:
#             yield_farm_id: posi-farm-busd-posi
#       withdraw:
#         wallet_id: farm-wallet
#         withdraw_wallet_id: busd-vault
