[package]
name = "mfm_machine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
mfm_machine_derive = { path = "../machine-derive-legacy" }
rand = { workspace = true } 
log = "0.4"
async-trait = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
