[package]
name = "mfm-op-evm-deploy-configure-validate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

mfm-evm-deploy-configure-validate-config = { path = "../../evm-deploy-configure-validate-config" }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-state-common = { path = "../../states/common" }
mfm-op-evm-write = { path = "../evm-write-op" }

[dev-dependencies]
tokio = { workspace = true }
