[package]
name = "mfm-op-evm-deploy-configure-validate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

mfm-canonical = { path = "../../kernel/canonical" }
mfm-certify = { path = "../../kernel/certify" }
mfm-evm-dcv-model = { path = "../../evm-dcv-model" }
mfm-evm-deploy-configure-validate-config = { path = "../../evm-deploy-configure-validate-config" }
mfm-ids = { path = "../../kernel/ids" }
mfm-program = { path = "../../kernel/program" }
mfm-spec = { path = "../../kernel/spec" }
mfm-state-evm-dcv = { path = "../../states/evm-dcv" }

[dev-dependencies]
tokio = { workspace = true }
trybuild = "1.0"
