[package]
name = "mfm-op-keystore-tx"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }

mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-op-common = { path = "../common" }
mfm-op-keystore-common = { path = "../keystore-common" }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
tempfile = "3.0"
mfm-transports-local-fs = { path = "../../transports/local-fs" }
mfm-transports-local-keystore = { path = "../../transports/local-keystore" }
