[package]
name = "mfm-op-nix-app"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-state-common = { path = "../../states/common" }

[dev-dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
mfm-collectors-nix-exec = { path = "../../collectors/nix-exec" }
mfm-transports-exec = { path = "../../transports/exec" }
