[package]
name = "mfm-op-nix-app"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-op-common = { path = "../common" }

[dev-dependencies]
uuid = { version = "1.8.0", features = ["v4"] }
mfm-collectors-nix-exec = { path = "../../collectors/nix-exec" }
