[package]
name = "mfm_core"
version = "0.1.29"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mfm_core"
path = "src/lib.rs"

[dependencies]
mfm_machine_derive = { path = "../mfm_machine_derive" }
mfm_machine = { path = "../mfm_machine" }
serde = { workspace = true }
zeroize = "1.7"
serde_json = { workspace = true }
serde_derive = { workspace = true }
anyhow = { workspace = true }
serde_yaml = { workspace = true }
tari_utilities = "0.8.0"
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-json-abi = { workspace = true }
alloy-dyn-abi = { workspace = true }
alloy-provider = { workspace = true }
alloy-contract = { workspace = true }
alloy-consensus = { workspace = true }
alloy-network = { workspace = true }
alloy-rpc-client = { workspace = true }
alloy-transport-http = { workspace = true }
alloy-signer = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
url = { workspace = true }
ring = { workspace = true }
pbkdf2 = "0.12"
base64 = "0.21"
rand = { workspace = true }
sha2 = "0.10"
sha3 = "0.10"
k256 = "0.13"
generic-array = "0.14"
crypto-common = "0.1"
cipher = "0.4"
hex = { workspace = true }
lazy_static = "1.5.0"
reqwest = { version = "0.12.14", features = ["json"] }
tiny-keccak = { version = "2.0", features = ["keccak"] }

# bls keystore dependencies
eth2_keystore = "0.4.0" # trying original name with a common version
dirs-next = "2.0"

[dev-dependencies]
tempfile = "3.8"
