auth_methods:
  - { type: wallet, private_key: YOUR_PRIVATE_KEY }

networks:
  bsc:
    kind: evm
    name: bsc
    symbol: bnb
    chain_id: 56
    node_url_http: https://bsc-dataseed.binance.org
    # node_url_grpc: 
    # node_url_failover: 
    blockexplorer_url: https://bscscan.com
    min_balance_coin: 0.1
    wrapped_token: wbnb
    decimals: 18
  polygon:
    kind: evm
    name: polygon
    symbol: matic
    chain_id: 137
    node_url_http: https://polygon-rpc.com/
    # node_url_grpc: 
    # node_url_failover: 
    blockexplorer_url: https://polygonscan.com/
    min_balance_coin: 1
    wrapped_token: wmatic
    decimals: 18

dexes:
  pancake_swap_v2:
    name: pancake_swap_v2
    kind: uniswap_v2
    router_address: 0x10ED43C718714eb63d5aA57B78B54704E256024E
    factory_address: 0xca143ce32fe78f1f7019d7d551a6402fc5350c73
    network_id: bsc
  quickswap_v2:
    name: quickswap_v2
    kind: uniswap_v2
    router_address: 0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff
    factory_address: 0x5757371414417b8c6caad45baef941abc7d3ab32
    network_id: polygon
  sushi_swap_polygon:
    name: sushi_swap_polygon
    kind: uniswap_v2
    router_address: 0x1b02da8cb0d097eb8d57a175b88c7d8b47997506
    factory_address: 0xc35dadb65012ec5796536bd9864ed8773abc74c4
    network_id: polygon
  biswap:
    name: biswap
    kind: uniswap_v2
    router_address: 0x3a6d8ca21d1cf76f653a67577fa0d27453350dd8
    factory_address: 0x858e3312ed3a876947ea49d572a7c42de08af7ee
    network_id: bsc

tokens:
  qidao:
    networks:
      polygon:
        name: qidao
        kind: erc20
        network_id: polygon
        address: 0x580a84c73811e1839f75d86d75d88cca0c241ff4
        slippage: 2
        path_token: weth
  dquick:
    kind: token
    networks:
      polygon:
        name: dquick
        kind: erc20
        network_id: polygon
        address: 0xf28164a485b0b2c90639e47b0f377b4a438a16b1
        slippage: 2
        path_token: weth
  xrp:
    kind: token
    networks:
      bsc:
        name: xrp
        kind: erc20
        network_id: bsc
        address: 0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE
        slippage: 2
        path_token: wbnb
  link:
    kind: token
    networks:
      bsc:
        name: link
        kind: erc20
        network_id: bsc
        address: 0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD
        slippage: 2
        path_token: wbnb
  gala:
    kind: token
    networks:
      bsc:
        name: gala
        kind: erc20
        network_id: bsc
        address: 0x7dDEE176F665cD201F93eEDE625770E2fD911990
        slippage: 2
        path_token: wbnb
  near:
    kind: token
    networks:
      bsc:
        name: near
        kind: erc20
        network_id: bsc
        address: 0x1Fa4a73a3F0133f0025378af00236f3aBDEE5D63
        slippage: 2
        path_token: wbnb
  luna:
    kind: token
    networks:
      bsc:
        name: luna
        kind: erc20
        network_id: bsc
        address: 0x156ab3346823B651294766e23e6Cf87254d68962
        slippage: 2
        path_token: wbnb
  wmatic:
    kind: token
    networks:
      bsc:
        name: wmatic
        kind: erc20
        network_id: bsc
        address: 0xcc42724c6683b7e57334c4e856f4c9965ed682bd
        slippage: 2
        path_token: wbnb
      polygon:
        name: wmatic
        kind: erc20
        network_id: polygon
        address: 0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270
        slippage: 2
        path_token: weth
  anonq:
    kind: token
    networks:
      bsc:
        name: anonq
        kind: erc20
        network_id: bsc
        address: 0xf393138616cd6DD367171eaA59c2eaEE420a32b9
        slippage: 2
        path_token: wbnb
  busd:
    kind: token
    networks:
      bsc:
        name: busd
        kind: erc20
        network_id: bsc
        address: 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
        slippage: 2
        path_token: wbnb
  wbnb:
    kind: token
    networks:
      bsc:
        name: wbnb
        kind: erc20
        network_id: bsc
        address: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
        slippage: 2
        path_token: wbnb
  weth:
    kind: token
    networks:
      bsc:
        name: weth
        kind: erc20
        network_id: bsc
        address: 0x2170ed0880ac9a755fd29b2688956bd959f933f8
        slippage: 2
        path_token: wbnb
      polygon:
        name: weth
        kind: erc20
        network_id: polygon
        address: 0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619
        slippage: 2
        path_token: weth
  btc:
    kind: token
    networks:
      bsc:
        name: btc
        kind: erc20
        network_id: bsc
        address: 0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c
        slippage: 2
        path_token: wbnb
  sol:
    kind: token
    networks:
      bsc:
        name: sol
        kind: erc20
        network_id: bsc
        address: 0x570A5D26f7765Ecb712C0924E4De545B89fD43dF
        slippage: 2
        path_token: wbnb
      polygon:
        name: sol
        kind: erc20
        network_id: polygon
        address: 0x7dff46370e9ea5f0bad3c4e29711ad50062ea7a4
        slippage: 2
        path_token: weth
  posi:
    kind: token
    networks:
      bsc:
        name: posi
        kind: erc20
        network_id: bsc
        address: 0x5ca42204cdaa70d5c773946e69de942b85ca6706
        slippage: 2
        path_token: wbnb
  cake:
    kind: token
    networks:
      bsc:
        name: cake
        kind: erc20
        network_id: bsc
        address: 0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
        slippage: 2
        path_token: wbnb
  pacoca:
    kind: token
    networks:
      bsc:
        name: pacoca
        kind: erc20
        network_id: bsc
        address: 0x55671114d774ee99d653d6c12460c780a67f1d18
        slippage: 1
        path_token: wbnb
  safemoon:
    kind: token
    networks:
      bsc:
        name: safemoon
        kind: erc20
        network_id: bsc
        address: 0x42981d0bfbAf196529376EE702F2a9Eb9092fcB5
        slippage: 1
        path_token: wbnb
  grt:
    kind: token
    networks:
      polygon:
        name: grt
        kind: erc20
        network_id: polygon
        address: 0x5fe2b58c013d7601147dcdd68c143a77499f5531
        slippage: 1
        path_token: weth
  usdc:
    kind: token
    networks:
      polygon:
        name: usdc
        kind: erc20
        network_id: polygon
        address: 0x2791bca1f2de4661ed88a30c99a7a9449aa84174
        slippage: 1
        path_token: wmatic
      bsc:
        name: usdc
        kind: erc20
        network_id: bsc
        address: 0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d
        slippage: 1
        path_token: wbnb
  usdt:
    kind: token
    networks:
      bsc:
        name: usdt
        kind: erc20
        network_id: bsc
        address: 0x55d398326f99059ff775485246999027b3197955
        slippage: 1
        path_token: wbnb
  baby:
    kind: token
    networks:
      bsc:
        name: baby
        kind: erc20
        network_id: bsc
        address: 0x53e562b9b7e5e94b81f10e96ee70ad06df3d2657
        slippage: 1
        path_token: usdt
  bal:
    kind: token
    networks:
      polygon:
        name: bal
        kind: erc20
        network_id: polygon
        address: 0x9a71012B13CA4d3D0Cdc72A177DF3ef03b0E76A3
        slippage: 3
        path_token: weth
  avax:
    kind: token
    networks:
      polygon:
        name: avax
        kind: erc20
        network_id: polygon
        address: 0x2c89bbc92bd86f8075d1decc58c7f4e0107f286b
        slippage: 2
        path_token: weth
