[package]
name = "mfm-op-keystore"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-collectors-local-keystore = { path = "../../collectors/local-keystore" }
mfm-evm-core = { path = "../../evm-core" }
mfm-state-common = { path = "../../states/common" }
mfm-state-keystore = { path = "../../states/keystore" }
