[package]
name = "mfm-app"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }

mfm-machine = { path = "../machine" }
mfm-sdk = { path = "../sdk" }
mfm-collectors-evm-jsonrpc-http = { path = "../collectors/evm-jsonrpc-http" }
mfm-collectors-nix-exec = { path = "../collectors/nix-exec" }
mfm-op-proof = { path = "../ops/proof-op" }
mfm-transports-local-fs = { path = "../transports/local-fs" }
mfm-transports-local-evm = { path = "../transports/local-evm" }
mfm-transports-local-keystore = { path = "../transports/local-keystore" }
mfm-transports-proof = { path = "../transports/proof" }
mfm-op-keystore-tx = { path = "../ops/keystore-tx-op" }
mfm-op-keystore-admin = { path = "../ops/keystore-admin-op" }
mfm-op-evm-read = { path = "../ops/evm-read-op" }
mfm-op-evm-write = { path = "../ops/evm-write-op" }
mfm-op-evm-deploy-configure-validate = { path = "../ops/evm-deploy-configure-validate-op" }
mfm-op-portfolio-tracker = { path = "../ops/portfolio-tracker-op" }
mfm-op-nix-app = { path = "../ops/nix-app-op" }
mfm-op-aave-v3-origin-adapt = { path = "../ops/aave-v3-origin-adapt-op" }
mfm-artifact-store-fs = { path = "../storages/artifact-store-fs" }
mfm-artifact-store-s3 = { path = "../storages/artifact-store-s3" }
mfm-event-store-postgres = { path = "../storages/event-store-postgres" }

[dev-dependencies]
tokio = { workspace = true }
