[package]
name = "mfm-op-portfolio-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
alloy-primitives = { workspace = true, features = ["serde"] }

mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-op-common = { path = "../common" }

[dev-dependencies]
tokio = { workspace = true }
