[package]
name = "mfm-op-evm-read"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-state-common = { path = "../../states/common" }
mfm-evm-runtime = { path = "../../evm-runtime" }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
