[package]
name = "mfm-collectors-local-evm"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { workspace = true }
serde_json = { workspace = true }
mfm-evm-core = { path = "../../evm-core", version = "0.1.0" }
mfm-machine = { path = "../../machine", version = "0.1.0" }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
