[package]
name = "mfm-collectors-nix-exec"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-transports-process-exec = { path = "../../transports/process-exec" }

[dev-dependencies]
uuid = { version = "1.8.0", features = ["v4"] }
