[package]
name = "mfm-state-common"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-collectors-nix = { path = "../../collectors/nix" }
mfm-collectors-exec = { path = "../../collectors/exec" }

[dev-dependencies]
