[package]
name = "mfm-op-common"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-collectors-evm = { path = "../../collectors/evm" }

[dev-dependencies]
tokio = { workspace = true }
