[package]
name = "mfm_machine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
serde = "1.0.188"
serde_derive = "1.0.189"
serde_json = "1.0.107"
mfm_machine_derive = { path = "../mfm_machine_derive" }
rand = "0.8.5" 

