[package]
name = "mfm_machine"
version = "0.1.0"
edition = "2021"

[dependencies]
mfm_machine_derive = { path = "../mfm_machine_derive" } # Keep existing path dependency

# Dependencies moved from workspace
anyhow = "1.0.75"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.193"
serde_json = "1.0.108"
rand = "0.9"
