[package]
name = "mfm-collectors-local-keystore"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
url = { workspace = true }
mfm-machine = { path = "../../machine" }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
