[package]
name = "mfm-transports-local-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
mfm-machine = { path = "../../machine" }
mfm-collectors-local-fs = { path = "../../collectors/local-fs" }
