[package]
name = "mfm-op-aave-v3-common"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

mfm-machine = { path = "../../machine" }
mfm-collectors-evm = { path = "../../collectors/evm" }
mfm-op-common = { path = "../common" }
mfm-evm-core = { path = "../../evm-core" }
mfm-evm-runtime = { path = "../../evm-runtime" }

[dev-dependencies]
tokio = { workspace = true }
