[package]
name = "mfm-artifact-store-secret"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
mfm-machine = { path = "../../machine" }
ring = { workspace = true }
hex = { workspace = true }
zeroize = "1.7"

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3.0"
mfm-artifact-store-fs = { path = "../artifact-store-fs" }
