[package]
name = "mfm-op-aave-v3-origin-adapt"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-state-common = { path = "../../states/common" }
mfm-state-aave-v3 = { path = "../../states/aave-v3" }
