[package]
name = "mfm-op-aave-v3-origin-adapt"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

mfm-machine = { path = "../../machine" }
mfm-sdk = { path = "../../sdk" }
mfm-op-common = { path = "../common" }
mfm-op-aave-v3-common = { path = "../aave-v3-common" }
