[package]
name = "mfm-live-adapter-authority-prototype"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "mfm_live_adapter_authority_prototype"
path = "src/lib.rs"

[dependencies]
mfm-program-authority-prototype = { path = "../program" }
mfm-runtime-authority-prototype = { path = "../runtime" }

[dev-dependencies]
mfm-store-authority-prototype = { path = "../store" }
