[package]
name = "mfm-app-legacy"
version = "0.1.0"
edition = "2021"

[lib]
name = "mfm_app"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }

mfm-machine = { path = "../machine" }
mfm-evm-deploy-configure-validate-config = { path = "../evm-deploy-configure-validate-config" }
mfm-sdk = { path = "../sdk" }
mfm-collectors-nix-exec = { path = "../collectors/nix-exec" }
mfm-transports-exec = { path = "../transports/exec" }
mfm-transports-local-fs = { path = "../transports/local-fs" }
mfm-transports-local-evm = { path = "../transports/local-evm" }
mfm-transports-local-keystore = { path = "../transports/local-keystore" }
mfm-transports-rpc-control = { path = "../transports/rpc-control" }
mfm-op-keystore = { path = "../ops/keystore-op" }
mfm-op-evm-read = { path = "../ops/evm-read-op" }
mfm-op-evm-write = { path = "../ops/evm-write-op" }
mfm-op-nix-app = { path = "../ops/nix-app-op" }
mfm-artifact-store-fs = { path = "../storages/artifact-store-fs" }
mfm-artifact-store-secret = { path = "../storages/artifact-store-secret" }
mfm-artifact-store-s3 = { path = "../storages/artifact-store-s3" }
mfm-stream-store-postgres = { path = "../storages/stream-store-postgres" }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
